version: "3.4"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: ${BUILD_TARGET}
        image: ${DOCKER_IMAGE_PREFIX}.web
        env_file:
            - .env
